const actionTypes = Object.freeze({
    //Post
    GET_WORKOUTS_SUCCESS: 'GET_WORKOUTS_SUCCESS',
    GET_WORKOUT_SUCCESS: 'GET_WORKOUT_SUCCESS',
    CREATE_WORKOUT_SUCCESS: 'CREATE_WORKOUT_SUCCESS',
    DELETE_WORKOUT_SUCCESS: 'DELETE_WORKOUT_SUCCESS',
    UPDATE_WORDOUT_SUCCESS: 'UPDATE_WORDOUT_SUCCESS',

    //User
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS'


})

export default actionTypes;